student(102,'petrov').
student(101,'petrovski').
student(104,'ivanov').
student(102,'ivanovski').
student(104,'zaporogcev').
student(101,'sidorov').
student(103,'sidorkin').
student(102,'bitcoinov').
student(103,'efircina').
student(103,'siplusplusov').
student(103,'programmistov').
student(104,'djavo').
student(103,'klaviaturnikova').
student(101,'mishin').
student(104,'full').
student(101,'bezumnikov').
student(102,'sharpin').
student(104,'krugloschitalkin').
student(103,'reshetnikov').
student(102,'exel').
student(102,'tekstopisov').
student(103,'tekstopisova').
student(101,'gustobukvennikova').
student(102,'kriptovalutnikov').
student(104,'blockchains').
student(102,'azurin').
student(103,'vebservisov').
student(102,'krugotlichnikov').
subject('lp','logic programming').
subject('mth','mathematical analysis').
subject('fp','functional programming').
subject('inf','informatics').
subject('eng','English').
subject('psy','psychology').
grade('petrov','lp',2).
grade('petrov','mth',3).
grade('petrov','fp',5).
grade('petrov','inf',4).
grade('petrov','eng',4).
grade('petrov','psy',3).
grade('petrovski','lp',5).
grade('petrovski','mth',5).
grade('petrovski','fp',5).
grade('petrovski','inf',4).
grade('petrovski','eng',5).
grade('petrovski','psy',3).
grade('ivanov','lp',5).
grade('ivanov','mth',3).
grade('ivanov','fp',4).
grade('ivanov','inf',5).
grade('ivanov','eng',5).
grade('ivanov','psy',5).
grade('ivanovski','lp',3).
grade('ivanovski','mth',5).
grade('ivanovski','fp',2).
grade('ivanovski','inf',3).
grade('ivanovski','eng',5).
grade('ivanovski','psy',5).
grade('zaporogcev','lp',2).
grade('zaporogcev','mth',2).
grade('zaporogcev','fp',4).
grade('zaporogcev','inf',3).
grade('zaporogcev','eng',4).
grade('zaporogcev','psy',4).
grade('sidorov','lp',4).
grade('sidorov','mth',4).
grade('sidorov','fp',4).
grade('sidorov','inf',4).
grade('sidorov','eng',3).
grade('sidorov','psy',4).
grade('sidorkin','lp',4).
grade('sidorkin','mth',5).
grade('sidorkin','fp',4).
grade('sidorkin','inf',3).
grade('sidorkin','eng',4).
grade('sidorkin','psy',4).
grade('bitcoinov','lp',5).
grade('bitcoinov','mth',4).
grade('bitcoinov','fp',3).
grade('bitcoinov','inf',4).
grade('bitcoinov','eng',3).
grade('bitcoinov','psy',2).
grade('efircina','lp',2).
grade('efircina','mth',4).
grade('efircina','fp',3).
grade('efircina','inf',2).
grade('efircina','eng',2).
grade('efircina','psy',4).
grade('siplusplusov','lp',4).
grade('siplusplusov','mth',4).
grade('siplusplusov','fp',4).
grade('siplusplusov','inf',5).
grade('siplusplusov','eng',4).
grade('siplusplusov','psy',4).
grade('programmistov','lp',5).
grade('programmistov','mth',4).
grade('programmistov','fp',3).
grade('programmistov','inf',3).
grade('programmistov','eng',5).
grade('programmistov','psy',4).
grade('djavo','lp',4).
grade('djavo','mth',4).
grade('djavo','fp',3).
grade('djavo','inf',2).
grade('djavo','eng',3).
grade('djavo','psy',5).
grade('klaviaturnikova','lp',4).
grade('klaviaturnikova','mth',5).
grade('klaviaturnikova','fp',3).
grade('klaviaturnikova','inf',5).
grade('klaviaturnikova','eng',4).
grade('klaviaturnikova','psy',4).
grade('mishin','lp',5).
grade('mishin','mth',4).
grade('mishin','fp',5).
grade('mishin','inf',4).
grade('mishin','eng',3).
grade('mishin','psy',3).
grade('full','lp',4).
grade('full','mth',4).
grade('full','fp',4).
grade('full','inf',5).
grade('full','eng',5).
grade('full','psy',5).
grade('bezumnikov','lp',3).
grade('bezumnikov','mth',5).
grade('bezumnikov','fp',3).
grade('bezumnikov','inf',2).
grade('bezumnikov','eng',4).
grade('bezumnikov','psy',3).
grade('sharpin','lp',3).
grade('sharpin','mth',2).
grade('sharpin','fp',4).
grade('sharpin','inf',5).
grade('sharpin','eng',5).
grade('sharpin','psy',5).
grade('krugloschitalkin','lp',5).
grade('krugloschitalkin','mth',2).
grade('krugloschitalkin','fp',4).
grade('krugloschitalkin','inf',3).
grade('krugloschitalkin','eng',4).
grade('krugloschitalkin','psy',3).
grade('reshetnikov','lp',4).
grade('reshetnikov','mth',4).
grade('reshetnikov','fp',5).
grade('reshetnikov','inf',3).
grade('reshetnikov','eng',5).
grade('reshetnikov','psy',3).
grade('exel','lp',4).
grade('exel','mth',2).
grade('exel','fp',4).
grade('exel','inf',3).
grade('exel','eng',5).
grade('exel','psy',4).
grade('tekstopisov','lp',2).
grade('tekstopisov','mth',5).
grade('tekstopisov','fp',4).
grade('tekstopisov','inf',3).
grade('tekstopisov','eng',5).
grade('tekstopisov','psy',3).
grade('tekstopisova','lp',4).
grade('tekstopisova','mth',4).
grade('tekstopisova','fp',4).
grade('tekstopisova','inf',3).
grade('tekstopisova','eng',5).
grade('tekstopisova','psy',2).
grade('gustobukvennikova','lp',5).
grade('gustobukvennikova','mth',2).
grade('gustobukvennikova','fp',4).
grade('gustobukvennikova','inf',5).
grade('gustobukvennikova','eng',4).
grade('gustobukvennikova','psy',3).
grade('kriptovalutnikov','lp',5).
grade('kriptovalutnikov','mth',2).
grade('kriptovalutnikov','fp',2).
grade('kriptovalutnikov','inf',3).
grade('kriptovalutnikov','eng',4).
grade('kriptovalutnikov','psy',2).
grade('blockchains','lp',5).
grade('blockchains','mth',2).
grade('blockchains','fp',5).
grade('blockchains','inf',3).
grade('blockchains','eng',4).
grade('blockchains','psy',5).
grade('azurin','lp',4).
grade('azurin','mth',2).
grade('azurin','fp',4).
grade('azurin','inf',3).
grade('azurin','eng',5).
grade('azurin','psy',2).
grade('vebservisov','lp',3).
grade('vebservisov','mth',4).
grade('vebservisov','fp',3).
grade('vebservisov','inf',3).
grade('vebservisov','eng',5).
grade('vebservisov','psy',2).
grade('krugotlichnikov','lp',4).
grade('krugotlichnikov','mth',3).
grade('krugotlichnikov','fp',5).
grade('krugotlichnikov','inf',2).
grade('krugotlichnikov','eng',3).
grade('krugotlichnikov','psy',5).
